import type {
  JointPose,
  MovementDefinition,
  MovementDiscipline,
  MovementPhase,
  MovementView,
  MotionFamily,
} from "./types";

type Side = MovementPhase["weightSide"];
type Position = MovementDefinition["position"];

function phase(
  id: string,
  label: string,
  progress: number,
  bodyX: number,
  bodyY: number,
  weightSide: Side,
  joints: JointPose,
  bodyRotation = 0,
  bodyScaleX = 1,
  bodyScaleY = 1,
): MovementPhase {
  return {
    id,
    label,
    progress,
    bodyX,
    bodyY,
    bodyRotation,
    bodyScaleX,
    bodyScaleY,
    weightSide,
    joints,
  };
}

type MovementSeed = {
  id: MovementDefinition["id"];
  title: string;
  discipline: MovementDiscipline;
  description: string;
  preferredView: MovementView;
  startingPose: string;
  position?: Position;
  motionFamily: MotionFamily;
  durationMs?: number;
  easing?: string;
  phases: MovementPhase[];
  howTo: [string, string, string, ...string[]];
  accessibility?: string;
  reducedPhaseIndexes?: [number, number, number];
  allowedWithBurqa?: boolean;
};

function movement(seed: MovementSeed): MovementDefinition {
  const reduced = seed.reducedPhaseIndexes ?? [
    0,
    Math.floor((seed.phases.length - 1) / 2),
    seed.phases.length - 1,
  ];
  return {
    ...seed,
    position: seed.position ?? "standing",
    durationMs: seed.durationMs ?? 5_200,
    easing: seed.easing ?? "cubic-bezier(0.45, 0, 0.22, 1)",
    repeats: true,
    instruction: seed.howTo.join(" "),
    accessibility:
      seed.accessibility ??
      "Use the selected seated, supported, limited-range, or one-arm form. Keep every joint within a comfortable range.",
    reducedMotionSteps: [
      seed.phases[reduced[0]].label,
      seed.phases[reduced[1]].label,
      seed.phases[reduced[2]].label,
    ],
    reducedPhaseIndexes: reduced,
    cautions: [
      "Pause if the movement increases discomfort, dizziness, pain, or instability.",
    ],
    allowedWithBurqa: seed.allowedWithBurqa ?? false,
  };
}

export const movementPractices: MovementDefinition[] = [
  movement({
    id: "riseSink",
    title: "Rise and sink",
    discipline: "Tai chi",
    description: "Float the arms as the legs lengthen, then lower them as the knees soften.",
    preferredView: "side",
    startingPose: "Stand with feet parallel and knees unlocked; let both hands rest near the thighs.",
    motionFamily: "rise",
    allowedWithBurqa: true,
    howTo: [
      "Stand with the feet about hip-width apart and let the knees remain soft.",
      "As the legs lengthen, float both hands forward to about chest height with rounded elbows.",
      "Bend the knees gently and lower the hands in front of the body.",
      "Return to the starting height without locking the knees.",
    ],
    phases: [
      phase("ready", "Feet parallel; hands rest low.", 0, 0, 4, "center", { leftKnee: 8, rightKnee: -8, leftShoulder: 3, rightShoulder: -3, leftElbow: 5, rightElbow: -5 }),
      phase("float", "Lengthen the legs and float both forearms to chest height.", 0.34, 0, -5, "center", { leftKnee: 1, rightKnee: -1, leftShoulder: 52, rightShoulder: -52, leftElbow: -38, rightElbow: 38 }),
      phase("sink", "Lower the hands while both knees bend.", 0.7, 0, 11, "center", { leftKnee: 24, rightKnee: -24, leftShoulder: 18, rightShoulder: -18, leftElbow: -14, rightElbow: 14 }),
      phase("ready-again", "Return to the parallel starting base.", 1, 0, 4, "center", { leftKnee: 8, rightKnee: -8, leftShoulder: 3, rightShoulder: -3, leftElbow: 5, rightElbow: -5 }),
    ],
  }),
  movement({
    id: "opening",
    title: "Opening and closing",
    discipline: "Tai chi",
    description: "Bring rounded forearms together, open them to shoulder width, and close again.",
    preferredView: "front",
    startingPose: "Stand evenly with elbows rounded and palms facing one another in front of the chest.",
    motionFamily: "rise",
    allowedWithBurqa: true,
    howTo: [
      "Hold both hands in front of the chest as if resting them around a large ball.",
      "Separate the hands to shoulder width without pulling the shoulder blades together.",
      "Bring the hands back toward one another while keeping the elbows rounded.",
      "Let the knees soften slightly as the hands close.",
    ],
    phases: [
      phase("center", "Rounded hands face one another at the center.", 0, 0, 1, "center", { leftShoulder: 38, rightShoulder: -38, leftElbow: -52, rightElbow: 52 }),
      phase("open", "Open both hands to shoulder width.", 0.42, 0, -2, "center", { leftShoulder: 78, rightShoulder: -78, leftElbow: -12, rightElbow: 12 }),
      phase("close", "Close the hands toward the center as the knees soften.", 0.76, 0, 5, "center", { leftKnee: 12, rightKnee: -12, leftShoulder: 38, rightShoulder: -38, leftElbow: -52, rightElbow: 52 }),
      phase("center-again", "Return to the rounded center.", 1, 0, 1, "center", { leftShoulder: 38, rightShoulder: -38, leftElbow: -52, rightElbow: 52 }),
    ],
  }),
  movement({
    id: "jointCircles",
    title: "Joint circles",
    discipline: "Tai chi",
    description: "Make visible circles at the shoulders and elbows without throwing the arms.",
    preferredView: "front",
    startingPose: "Stand evenly with the upper arms close to the ribs and forearms forward.",
    motionFamily: "circle",
    durationMs: 6_200,
    easing: "linear",
    allowedWithBurqa: true,
    howTo: [
      "Keep the upper arms close to the ribs and bend both elbows.",
      "Lead the elbows forward and upward, then let them travel outward.",
      "Continue the circle downward and back toward the ribs.",
      "Keep the chest quiet so the elbow pathway stays easy to see.",
    ],
    phases: [
      phase("low", "Elbows begin low beside the ribs.", 0, 0, 1, "center", { leftShoulder: 8, rightShoulder: -8, leftElbow: -72, rightElbow: 72 }),
      phase("forward", "Elbows travel forward and upward.", 0.25, 0, -2, "center", { leftShoulder: 42, rightShoulder: -42, leftElbow: -86, rightElbow: 86 }),
      phase("wide", "Elbows open visibly to the sides.", 0.5, 0, -3, "center", { leftShoulder: 76, rightShoulder: -76, leftElbow: -42, rightElbow: 42 }),
      phase("down", "Elbows circle down toward the ribs.", 0.75, 0, 2, "center", { leftShoulder: 24, rightShoulder: -24, leftElbow: -28, rightElbow: 28 }),
      phase("low-again", "Complete the circle at the ribs.", 1, 0, 1, "center", { leftShoulder: 8, rightShoulder: -8, leftElbow: -72, rightElbow: 72 }),
    ],
    reducedPhaseIndexes: [0, 2, 4],
  }),
  movement({
    id: "silkReeling",
    title: "Silk reeling",
    discipline: "Tai chi",
    description: "Turn the waist while one rounded arm spirals outward and returns.",
    preferredView: "side",
    startingPose: "Stand with more weight on the left leg and the right palm near the lower ribs.",
    motionFamily: "circle",
    durationMs: 6_400,
    easing: "linear",
    allowedWithBurqa: true,
    howTo: [
      "Place the right palm near the lower ribs and keep the elbow heavy.",
      "Shift toward the right leg while the waist turns and the right forearm spirals outward.",
      "Turn the palm as the arm reaches no farther than shoulder height.",
      "Shift back left and coil the elbow toward the ribs to begin again.",
    ],
    phases: [
      phase("coil", "Weight left; right palm coils near the ribs.", 0, -8, 3, "left", { torso: -5, leftKnee: 16, rightKnee: -6, leftShoulder: 18, leftElbow: -35, rightShoulder: -12, rightElbow: 76 }),
      phase("spiral-out", "Turn right and spiral the right forearm outward.", 0.36, 7, -2, "right", { torso: 7, leftKnee: 7, rightKnee: -18, leftShoulder: 28, leftElbow: -46, rightShoulder: -58, rightElbow: 30, rightHand: 35 }),
      phase("extend", "Finish the spiral with a rounded elbow.", 0.62, 11, -1, "right", { torso: 9, leftKnee: 6, rightKnee: -20, leftShoulder: 22, leftElbow: -38, rightShoulder: -72, rightElbow: 18, rightHand: 75 }),
      phase("recoil", "Shift left and draw the right elbow back to the ribs.", 0.84, -4, 2, "left", { torso: -2, leftKnee: 14, rightKnee: -8, leftShoulder: 18, leftElbow: -35, rightShoulder: -28, rightElbow: 58 }),
      phase("coil-again", "Return to the coiled starting shape.", 1, -8, 3, "left", { torso: -5, leftKnee: 16, rightKnee: -6, leftShoulder: 18, leftElbow: -35, rightShoulder: -12, rightElbow: 76 }),
    ],
    reducedPhaseIndexes: [0, 2, 4],
  }),
  movement({
    id: "cloudHands",
    title: "Cloud hands",
    discipline: "Tai chi",
    description: "Shift sideways while the upper and lower palms exchange places across the body.",
    preferredView: "front",
    startingPose: "Stand a little wider than the hips with weight toward the left foot.",
    motionFamily: "cloud",
    durationMs: 6_600,
    allowedWithBurqa: true,
    howTo: [
      "Shift toward the left foot while the left palm rises in front of the chest and the right palm lowers.",
      "Turn through the waist and let both hands pass the center without crossing at the wrists.",
      "Shift toward the right foot as the right palm rises and the left palm lowers.",
      "Keep both elbows rounded and reverse the pathway.",
    ],
    phases: [
      phase("left", "Weight left; left palm high and right palm low.", 0, -13, 3, "left", { torso: -5, leftKnee: 18, rightKnee: -5, leftShoulder: 48, leftElbow: -42, rightShoulder: -20, rightElbow: 18 }),
      phase("center", "Both rounded arms pass through the center.", 0.25, 0, -1, "center", { torso: 0, leftKnee: 10, rightKnee: -10, leftShoulder: 34, leftElbow: -58, rightShoulder: -34, rightElbow: 58 }),
      phase("right", "Weight right; right palm high and left palm low.", 0.5, 13, 3, "right", { torso: 5, leftKnee: 5, rightKnee: -18, leftShoulder: 20, leftElbow: -18, rightShoulder: -48, rightElbow: 42 }),
      phase("center-return", "Both rounded arms pass through the center.", 0.75, 0, -1, "center", { torso: 0, leftKnee: 10, rightKnee: -10, leftShoulder: 34, leftElbow: -58, rightShoulder: -34, rightElbow: 58 }),
      phase("left-again", "Return to the left-weighted shape.", 1, -13, 3, "left", { torso: -5, leftKnee: 18, rightKnee: -5, leftShoulder: 48, leftElbow: -42, rightShoulder: -20, rightElbow: 18 }),
    ],
    reducedPhaseIndexes: [0, 2, 4],
  }),
  movement({
    id: "partHorse",
    title: "Parting the horse’s mane",
    discipline: "Tai chi",
    description: "Step into a bow stance while the hands separate forward and down.",
    preferredView: "side",
    startingPose: "Begin with weight back and both hands rounded near the waist.",
    motionFamily: "form",
    howTo: [
      "Gather both hands near the waist with most of the weight on the back leg.",
      "Place the front heel and begin transferring weight into the front knee.",
      "Send the front-side hand forward and slightly upward while the other hand lowers beside the hip.",
      "Shift back and return both hands to the gathered shape.",
    ],
    phases: [
      phase("gather", "Weight back; both hands gather near the waist.", 0, -9, 4, "left", { torso: -4, leftHip: -8, leftKnee: 12, rightHip: 20, rightKnee: -16, leftShoulder: 16, leftElbow: -66, rightShoulder: -16, rightElbow: 66 }),
      phase("heel", "Place the forward heel without transferring all the weight.", 0.24, -3, 1, "left", { leftHip: -5, leftKnee: 8, rightHip: 32, rightKnee: -12, rightFoot: 16, leftShoulder: 24, leftElbow: -60, rightShoulder: -22, rightElbow: 58 }),
      phase("separate", "Transfer forward as one hand rises and the other lowers.", 0.62, 11, 0, "right", { torso: 6, leftHip: -16, leftKnee: 7, rightHip: 12, rightKnee: -24, leftShoulder: 64, leftElbow: -24, rightShoulder: -12, rightElbow: 24 }),
      phase("return", "Shift back and gather the hands.", 1, -9, 4, "left", { torso: -4, leftHip: -8, leftKnee: 12, rightHip: 20, rightKnee: -16, leftShoulder: 16, leftElbow: -66, rightShoulder: -16, rightElbow: 66 }),
    ],
  }),
  movement({
    id: "brushKnee",
    title: "Brush knee",
    discipline: "Tai chi",
    description: "Sweep one palm past the knee as the opposite palm presses forward.",
    preferredView: "side",
    startingPose: "Begin with weight back, the left hand near the shoulder, and the right hand near the hip.",
    motionFamily: "form",
    howTo: [
      "Keep most of the weight on the back leg and raise the pressing hand near the shoulder.",
      "Place the forward heel and sweep the opposite palm down beside the front knee.",
      "Transfer weight into the front leg while the raised palm presses forward.",
      "Keep the pressing elbow soft, then shift back to repeat.",
    ],
    phases: [
      phase("prepare", "Weight back; pressing palm waits near the shoulder.", 0, -10, 4, "left", { torso: -4, leftHip: -6, leftKnee: 12, rightHip: 22, rightKnee: -14, leftShoulder: 46, leftElbow: -42, rightShoulder: -52, rightElbow: 76 }),
      phase("brush", "Place the heel and sweep the left palm past the knee.", 0.32, -1, 2, "left", { torso: 1, leftHip: -12, leftKnee: 8, rightHip: 30, rightKnee: -18, leftShoulder: 6, leftElbow: -18, rightShoulder: -58, rightElbow: 62 }),
      phase("press", "Transfer forward and press the right palm.", 0.68, 12, 0, "right", { torso: 7, leftHip: -18, leftKnee: 6, rightHip: 10, rightKnee: -25, leftShoulder: 2, leftElbow: -8, rightShoulder: -72, rightElbow: 18 }),
      phase("prepare-again", "Shift back and prepare the hands again.", 1, -10, 4, "left", { torso: -4, leftHip: -6, leftKnee: 12, rightHip: 22, rightKnee: -14, leftShoulder: 46, leftElbow: -42, rightShoulder: -52, rightElbow: 76 }),
    ],
  }),
  movement({
    id: "wardOff",
    title: "Ward off",
    discipline: "Tai chi",
    description: "Carry a rounded forearm forward while the rear hand supports the shape.",
    preferredView: "side",
    startingPose: "Begin in a short bow stance with a rounded front forearm near the ribs.",
    motionFamily: "form",
    allowedWithBurqa: true,
    howTo: [
      "Round the front arm as though it rests around the side of a large ball.",
      "Keep the rear palm near the front forearm without squeezing the arms together.",
      "Transfer weight into the front leg and carry the rounded shape forward.",
      "Shift back without collapsing the elbow.",
    ],
    phases: [
      phase("receive", "Weight back; arms hold a rounded ball shape.", 0, -9, 3, "left", { torso: -4, leftKnee: 14, rightKnee: -10, leftShoulder: 34, leftElbow: -74, rightShoulder: -26, rightElbow: 64 }),
      phase("carry", "Transfer forward with the rounded forearm leading.", 0.52, 11, -1, "right", { torso: 6, leftKnee: 7, rightKnee: -23, leftShoulder: 58, leftElbow: -54, rightShoulder: -44, rightElbow: 70 }),
      phase("receive-again", "Shift back without dropping the elbow.", 1, -9, 3, "left", { torso: -4, leftKnee: 14, rightKnee: -10, leftShoulder: 34, leftElbow: -74, rightShoulder: -26, rightElbow: 64 }),
    ],
  }),
  movement({
    id: "repulseMonkey",
    title: "Repulse monkey",
    discipline: "Tai chi",
    description: "Step backward as one palm withdraws and the other presses forward.",
    preferredView: "side",
    startingPose: "Stand with the right palm forward and the left hand near the ribs.",
    motionFamily: "form",
    howTo: [
      "Begin with one palm forward and the other hand near the ribs.",
      "Reach the rear foot back and place the toes before transferring weight.",
      "Draw the forward palm toward the ribs as the other palm presses forward.",
      "Bring the front foot back under the body and prepare the opposite side.",
    ],
    phases: [
      phase("forward-palm", "Right palm forward; weight remains over the front foot.", 0, 8, 1, "right", { leftHip: -10, leftKnee: 7, rightHip: 12, rightKnee: -18, leftShoulder: 18, leftElbow: -58, rightShoulder: -72, rightElbow: 18 }),
      phase("step-back", "Reach the left toes backward.", 0.25, 2, 1, "right", { leftHip: -34, leftKnee: 22, leftFoot: -12, rightHip: 7, rightKnee: -16, leftShoulder: 28, leftElbow: -52, rightShoulder: -58, rightElbow: 28 }),
      phase("exchange", "Shift back while the left palm presses and the right withdraws.", 0.64, -11, 2, "left", { torso: -6, leftHip: -15, leftKnee: 22, rightHip: 16, rightKnee: -7, leftShoulder: 68, leftElbow: -20, rightShoulder: -20, rightElbow: 64 }),
      phase("forward-again", "Return to the forward-palm shape.", 1, 8, 1, "right", { leftHip: -10, leftKnee: 7, rightHip: 12, rightKnee: -18, leftShoulder: 18, leftElbow: -58, rightShoulder: -72, rightElbow: 18 }),
    ],
  }),
  movement({
    id: "goldenRooster",
    title: "Golden rooster",
    discipline: "Tai chi",
    description: "Stand on one leg while the opposite knee and hand rise together.",
    preferredView: "side",
    startingPose: "Stand evenly with a support point within reach if selected.",
    motionFamily: "balance",
    howTo: [
      "Shift all available weight into the left foot without locking the left knee.",
      "Draw the right knee upward in front of the hip.",
      "Raise the right hand with the knee while the left hand lowers.",
      "Place the right foot down before changing sides or repeating.",
    ],
    phases: [
      phase("root", "Root through the left foot.", 0, -5, 2, "left", { leftKnee: 10, rightKnee: -6, leftShoulder: 12, leftElbow: -18, rightShoulder: -16, rightElbow: 18 }),
      phase("gather", "Draw the right knee and right hand upward.", 0.42, -6, -7, "left", { leftHip: -3, leftKnee: 12, rightHip: -48, rightKnee: 86, rightFoot: -24, leftShoulder: 5, leftElbow: -12, rightShoulder: -62, rightElbow: 34 }),
      phase("hold", "Balance briefly with the lifted knee in front.", 0.62, -6, -8, "left", { leftHip: -3, leftKnee: 12, rightHip: -54, rightKnee: 92, rightFoot: -28, leftShoulder: 5, leftElbow: -12, rightShoulder: -72, rightElbow: 28 }),
      phase("lower", "Lower the right foot with control.", 1, -5, 2, "left", { leftKnee: 10, rightKnee: -6, leftShoulder: 12, leftElbow: -18, rightShoulder: -16, rightElbow: 18 }),
    ],
  }),
  movement({
    id: "whiteCrane",
    title: "White crane spreads wings",
    discipline: "Tai chi",
    description: "Settle onto the back leg while one hand rises and the other lowers.",
    preferredView: "front",
    startingPose: "Begin in a short stance with the right foot forward.",
    motionFamily: "balance",
    howTo: [
      "Shift most of the weight into the back leg and leave the front toes lightly touching.",
      "Lift the right hand above the forehead with a rounded elbow.",
      "Lower the left hand beside the hip.",
      "Keep the front foot light, then return to the short stance.",
    ],
    phases: [
      phase("short-stance", "Begin in a short, two-foot stance.", 0, 4, 1, "center", { leftKnee: 13, rightKnee: -14, leftShoulder: 24, leftElbow: -44, rightShoulder: -30, rightElbow: 44 }),
      phase("crane", "Settle back; right hand high, left hand low, front toes light.", 0.5, -9, 0, "left", { torso: -3, leftKnee: 20, rightHip: 24, rightKnee: -34, rightFoot: 24, leftShoulder: 3, leftElbow: -8, rightShoulder: -112, rightElbow: 28 }),
      phase("short-stance-again", "Return to the short, two-foot stance.", 1, 4, 1, "center", { leftKnee: 13, rightKnee: -14, leftShoulder: 24, leftElbow: -44, rightShoulder: -30, rightElbow: 44 }),
    ],
  }),
  movement({
    id: "sparrowTail",
    title: "Grasp the sparrow’s tail",
    discipline: "Tai chi",
    description: "Link ward off, roll back, press, and push through one continuous weight transfer.",
    preferredView: "side",
    startingPose: "Begin with weight back and both forearms rounded in front of the ribs.",
    motionFamily: "form",
    durationMs: 8_200,
    howTo: [
      "Transfer forward with one rounded forearm leading for ward off.",
      "Turn the waist and draw both hands back beside the rear hip for roll back.",
      "Bring the forearms together and transfer forward for press.",
      "Separate the palms, shift back, then push both palms forward as the weight returns.",
    ],
    phases: [
      phase("receive", "Weight back; forearms rounded.", 0, -10, 3, "left", { torso: -4, leftKnee: 16, rightKnee: -9, leftShoulder: 36, leftElbow: -66, rightShoulder: -28, rightElbow: 64 }),
      phase("ward-off", "Transfer forward with the rounded forearm.", 0.2, 10, -1, "right", { torso: 5, leftKnee: 8, rightKnee: -23, leftShoulder: 58, leftElbow: -48, rightShoulder: -42, rightElbow: 68 }),
      phase("roll-back", "Turn and draw both hands toward the rear hip.", 0.43, -7, 2, "left", { torso: -9, leftKnee: 18, rightKnee: -7, leftShoulder: 8, leftElbow: -46, rightShoulder: -12, rightElbow: 48 }),
      phase("press", "Join the forearms and transfer forward.", 0.65, 10, -1, "right", { torso: 4, leftKnee: 8, rightKnee: -22, leftShoulder: 48, leftElbow: -70, rightShoulder: -48, rightElbow: 70 }),
      phase("push", "Separate both palms and finish the forward push.", 0.82, 12, 0, "right", { torso: 6, leftKnee: 7, rightKnee: -24, leftShoulder: 68, leftElbow: -18, rightShoulder: -68, rightElbow: 18 }),
      phase("receive-again", "Shift back to the rounded beginning.", 1, -10, 3, "left", { torso: -4, leftKnee: 16, rightKnee: -9, leftShoulder: 36, leftElbow: -66, rightShoulder: -28, rightElbow: 64 }),
    ],
    reducedPhaseIndexes: [0, 2, 4],
  }),
  movement({
    id: "fairLady",
    title: "Fair lady works the shuttles",
    discipline: "Tai chi",
    description: "Step diagonally while one forearm shelters above and the opposite palm presses.",
    preferredView: "front",
    startingPose: "Begin with feet parallel and both hands gathered near the waist.",
    motionFamily: "form",
    howTo: [
      "Gather the hands near the waist and turn toward the front-right diagonal.",
      "Place the right heel diagonally and begin transferring weight.",
      "Raise the right forearm above the brow while the left palm presses toward the diagonal.",
      "Shift back and return the hands to the waist.",
    ],
    phases: [
      phase("gather", "Hands gather at the waist.", 0, -4, 3, "left", { torso: -3, leftKnee: 13, rightKnee: -9, leftShoulder: 14, leftElbow: -62, rightShoulder: -14, rightElbow: 62 }),
      phase("diagonal-step", "Place the right heel toward the diagonal.", 0.3, 2, 1, "left", { torso: 5, leftKnee: 9, rightHip: 28, rightKnee: -18, rightFoot: 18, leftShoulder: 28, leftElbow: -54, rightShoulder: -50, rightElbow: 48 }),
      phase("shuttle", "Transfer forward; shelter high and press with the other palm.", 0.68, 11, -1, "right", { torso: 8, leftKnee: 6, rightKnee: -24, leftShoulder: 66, leftElbow: -18, rightShoulder: -118, rightElbow: 38 }),
      phase("gather-again", "Shift back and gather the hands.", 1, -4, 3, "left", { torso: -3, leftKnee: 13, rightKnee: -9, leftShoulder: 14, leftElbow: -62, rightShoulder: -14, rightElbow: 62 }),
    ],
  }),
  movement({
    id: "snakeDown",
    title: "Snake creeps down",
    discipline: "Tai chi",
    description: "Lower into a deep side lunge while the other leg lengthens and one hand traces low.",
    preferredView: "front",
    startingPose: "Stand in a wide stance with weight centered and toes angled slightly outward.",
    motionFamily: "balance",
    durationMs: 6_800,
    howTo: [
      "Widen the stance and keep both feet in full contact with the floor.",
      "Shift toward the left and bend the left knee deeply while the right leg lengthens.",
      "Keep the spine long and trace the left hand toward the inside of the bent leg.",
      "Press through the left foot to return to the centered wide stance.",
    ],
    phases: [
      phase("wide", "Begin upright in a wide stance.", 0, 0, 0, "center", { leftHip: -18, leftKnee: 12, rightHip: 18, rightKnee: -12, leftShoulder: 30, leftElbow: -28, rightShoulder: -30, rightElbow: 28 }),
      phase("lower", "Shift left and bend the left knee deeply.", 0.46, -17, 18, "left", { torso: -13, leftHip: -30, leftKnee: 62, leftFoot: -10, rightHip: 34, rightKnee: -3, leftShoulder: 2, leftElbow: -8, rightShoulder: -56, rightElbow: 30 }, -5, 1.04, 0.9),
      phase("trace-low", "Keep the right leg long while the left hand traces low.", 0.66, -19, 23, "left", { torso: -17, leftHip: -34, leftKnee: 72, leftFoot: -12, rightHip: 38, rightKnee: 0, leftShoulder: -18, leftElbow: -10, rightShoulder: -62, rightElbow: 24 }, -7, 1.06, 0.86),
      phase("wide-again", "Press back to the centered wide stance.", 1, 0, 0, "center", { leftHip: -18, leftKnee: 12, rightHip: 18, rightKnee: -12, leftShoulder: 30, leftElbow: -28, rightShoulder: -30, rightElbow: 28 }),
    ],
  }),
  movement({
    id: "mountain",
    title: "Mountain pose",
    discipline: "Yoga",
    description: "Stand evenly with the head, ribs, pelvis, and feet stacked.",
    preferredView: "side",
    startingPose: "Stand with feet parallel, arms beside the body, and gaze level.",
    motionFamily: "still",
    allowedWithBurqa: true,
    howTo: [
      "Place the feet parallel and distribute weight across both heels and forefeet.",
      "Stack the pelvis under the ribs without tucking or arching strongly.",
      "Lengthen the back of the neck and let both arms hang beside the body.",
      "Keep breathing without changing the shape.",
    ],
    phases: [
      phase("arrive", "Weight rests evenly across both feet.", 0, 0, 1, "center", { leftKnee: 4, rightKnee: -4, leftShoulder: 2, rightShoulder: -2 }),
      phase("lengthen", "Ribs, pelvis, and head stack over the feet.", 0.5, 0, -3, "center", { head: 0, torso: 0, pelvis: 0, leftKnee: 1, rightKnee: -1 }),
      phase("arrive-again", "Remain tall without becoming rigid.", 1, 0, 1, "center", { leftKnee: 4, rightKnee: -4, leftShoulder: 2, rightShoulder: -2 }),
    ],
  }),
  movement({
    id: "catCow",
    title: "Cat–cow",
    discipline: "Yoga",
    description: "From hands and knees, alternate a rounded spine with a gently lengthened spine.",
    preferredView: "side",
    startingPose: "Come to hands and knees with wrists below shoulders and knees below hips.",
    position: "quadruped",
    motionFamily: "spine",
    durationMs: 7_000,
    howTo: [
      "Place the hands beneath the shoulders and the knees beneath the hips.",
      "Press the floor away, tuck the chin slightly, and round the middle back for cat.",
      "Tip the sitting bones back, lengthen the chest forward, and lift the gaze slightly for cow.",
      "Move between the two shapes without dropping into the shoulders.",
    ],
    phases: [
      phase("table", "Hands below shoulders; knees below hips.", 0, 0, -4, "center", { head: -74, torso: 0, leftShoulder: -76, rightShoulder: 76, leftElbow: 4, rightElbow: -4, leftHip: -72, rightHip: 72, leftKnee: 88, rightKnee: -88 }, 74, 1, 1),
      phase("cat", "Press the floor away and round the middle back.", 0.36, -2, -7, "center", { head: -62, torso: -7, leftShoulder: -78, rightShoulder: 78, leftElbow: 8, rightElbow: -8, leftHip: -68, rightHip: 68, leftKnee: 94, rightKnee: -94 }, 70, 1.02, 0.94),
      phase("cow", "Lengthen the chest forward and tip the sitting bones back.", 0.7, 3, 0, "center", { head: -86, torso: 8, leftShoulder: -72, rightShoulder: 72, leftElbow: 2, rightElbow: -2, leftHip: -78, rightHip: 78, leftKnee: 82, rightKnee: -82 }, 77, 1.02, 1.03),
      phase("table-again", "Return to the hands-and-knees table.", 1, 0, -4, "center", { head: -74, torso: 0, leftShoulder: -76, rightShoulder: 76, leftElbow: 4, rightElbow: -4, leftHip: -72, rightHip: 72, leftKnee: 88, rightKnee: -88 }, 74, 1, 1),
    ],
  }),
  movement({
    id: "chairPose",
    title: "Chair pose",
    discipline: "Yoga",
    description: "Bend the knees and send the hips backward while the arms reach forward or overhead.",
    preferredView: "side",
    startingPose: "Stand with feet parallel and arms beside the body.",
    motionFamily: "rise",
    howTo: [
      "Bend both knees and send the hips backward as though approaching a chair.",
      "Keep the chest lifted and the knees tracking in the same direction as the toes.",
      "Reach the arms forward or overhead without lifting the shoulders.",
      "Press through both feet to stand tall again.",
    ],
    phases: [
      phase("stand", "Stand tall with feet parallel.", 0, 0, 0, "center", { leftKnee: 3, rightKnee: -3, leftShoulder: 2, rightShoulder: -2 }),
      phase("sit-back", "Send the hips back and bend both knees.", 0.42, -5, 15, "center", { torso: 9, pelvis: -10, leftHip: -24, rightHip: 24, leftKnee: 52, rightKnee: -52, leftShoulder: 72, rightShoulder: -72, leftElbow: -12, rightElbow: 12 }, -2, 1.02, 0.92),
      phase("hold", "Keep the chest long while the arms reach.", 0.66, -7, 17, "center", { torso: 11, pelvis: -12, leftHip: -28, rightHip: 28, leftKnee: 58, rightKnee: -58, leftShoulder: 82, rightShoulder: -82, leftElbow: -8, rightElbow: 8 }, -3, 1.03, 0.9),
      phase("stand-again", "Press through both feet to stand.", 1, 0, 0, "center", { leftKnee: 3, rightKnee: -3, leftShoulder: 2, rightShoulder: -2 }),
    ],
  }),
  movement({
    id: "warriorTwo",
    title: "Warrior II",
    discipline: "Yoga",
    description: "Open into a wide stance, bend the front knee, and reach the arms in opposite directions.",
    preferredView: "front",
    startingPose: "Stand wide with the right toes turned out and the left foot angled slightly inward.",
    motionFamily: "balance",
    howTo: [
      "Step the feet wide and turn the right toes toward the right side.",
      "Bend the right knee over the right foot while the left leg stays long.",
      "Reach both arms horizontally, one over each leg.",
      "Stack the torso over the pelvis and look over the right fingertips.",
    ],
    phases: [
      phase("wide", "Feet wide; arms rest low.", 0, 0, 0, "center", { leftHip: -26, leftKnee: 5, rightHip: 26, rightKnee: -5, leftShoulder: 5, rightShoulder: -5 }),
      phase("warrior", "Bend the right knee and reach both arms horizontally.", 0.48, 10, 5, "right", { head: 4, leftHip: -31, leftKnee: 2, leftFoot: -8, rightHip: 24, rightKnee: -44, rightFoot: 18, leftShoulder: 88, leftElbow: -4, rightShoulder: -88, rightElbow: 4 }),
      phase("hold", "Keep the torso centered over the wide base.", 0.68, 10, 5, "right", { head: 4, torso: 0, leftHip: -31, leftKnee: 2, rightHip: 24, rightKnee: -44, leftShoulder: 90, rightShoulder: -90 }),
      phase("wide-again", "Straighten the front knee and lower the arms.", 1, 0, 0, "center", { leftHip: -26, leftKnee: 5, rightHip: 26, rightKnee: -5, leftShoulder: 5, rightShoulder: -5 }),
    ],
  }),
  movement({
    id: "treePose",
    title: "Tree pose",
    discipline: "Yoga",
    description: "Balance on one leg with the other foot resting below or above the knee.",
    preferredView: "front",
    startingPose: "Stand evenly with a support point within reach if selected.",
    motionFamily: "balance",
    howTo: [
      "Shift weight into the left foot and keep the left knee unlocked.",
      "Turn the right knee outward and place the right toes on the floor or the foot against the left calf or thigh—not the knee.",
      "Bring the palms together at the chest or raise them overhead.",
      "Lower the arms and place the right foot down before repeating.",
    ],
    phases: [
      phase("root", "Root through the left foot.", 0, -4, 1, "left", { leftKnee: 7, rightKnee: -5, leftShoulder: 16, leftElbow: -58, rightShoulder: -16, rightElbow: 58 }),
      phase("place-foot", "Turn the right knee out and place the foot against the standing leg.", 0.35, -5, -3, "left", { leftHip: -3, leftKnee: 9, rightHip: -48, rightKnee: 96, rightFoot: 32, leftShoulder: 28, leftElbow: -66, rightShoulder: -28, rightElbow: 66 }),
      phase("grow", "Keep the foot placed while both arms rise.", 0.68, -5, -6, "left", { leftHip: -3, leftKnee: 9, rightHip: -48, rightKnee: 96, rightFoot: 32, leftShoulder: 148, leftElbow: -12, rightShoulder: -148, rightElbow: 12 }),
      phase("root-again", "Lower the foot and return to two feet.", 1, -4, 1, "left", { leftKnee: 7, rightKnee: -5, leftShoulder: 16, leftElbow: -58, rightShoulder: -16, rightElbow: 58 }),
    ],
  }),
  movement({
    id: "toeTap",
    title: "Toe tap",
    discipline: "Tap",
    description: "Extend one foot, touch only the toe plate, and return without transferring weight.",
    preferredView: "side",
    startingPose: "Stand over the left leg with the right foot free and both knees soft.",
    motionFamily: "footwork",
    durationMs: 3_800,
    allowedWithBurqa: true,
    howTo: [
      "Keep weight over the left leg and release the right heel.",
      "Extend the right foot forward from the knee.",
      "Touch the right toe to the floor without placing weight on it.",
      "Bring the right foot back under the hip.",
    ],
    phases: [
      phase("support", "Weight stays over the left leg.", 0, -3, 1, "left", { leftKnee: 12, rightKnee: -8 }),
      phase("extend", "Extend the right foot forward from the knee.", 0.38, -2, -1, "left", { leftKnee: 13, rightHip: -22, rightKnee: 34, rightFoot: -24 }),
      phase("tap", "Touch the toe plate without transferring weight.", 0.58, -2, 1, "left", { leftKnee: 13, rightHip: -27, rightKnee: 24, rightFoot: -38 }),
      phase("support-again", "Return the right foot under the hip.", 1, -3, 1, "left", { leftKnee: 12, rightKnee: -8 }),
    ],
  }),
  movement({
    id: "heelDrop",
    title: "Heel drop",
    discipline: "Tap",
    description: "Lift one heel while the ball stays planted, then place the heel with a clear accent.",
    preferredView: "side",
    startingPose: "Stand evenly with the right ball of the foot planted.",
    motionFamily: "footwork",
    durationMs: 3_400,
    allowedWithBurqa: true,
    howTo: [
      "Keep the ball of the right foot on the floor.",
      "Lift the right heel by bending the ankle and knee slightly.",
      "Drop the heel to the floor without lifting the toe.",
      "Let the knee absorb the accent.",
    ],
    phases: [
      phase("flat", "Both feet begin flat.", 0, 0, 1, "center", { leftKnee: 7, rightKnee: -7, rightFoot: 0 }),
      phase("heel-up", "Keep the toe planted and lift the right heel.", 0.42, 2, -1, "left", { leftKnee: 9, rightKnee: -17, rightFoot: 28 }),
      phase("drop", "Place the right heel with a clear accent.", 0.58, 1, 3, "center", { leftKnee: 10, rightKnee: -12, rightFoot: -5 }),
      phase("flat-again", "Return to two flat feet.", 1, 0, 1, "center", { leftKnee: 7, rightKnee: -7, rightFoot: 0 }),
    ],
  }),
  movement({
    id: "shuffle",
    title: "Shuffle",
    discipline: "Tap",
    description: "Brush the toe forward and backward in two sounds while the thigh stays quiet.",
    preferredView: "side",
    startingPose: "Stand over the left leg with the right knee bent and the foot released.",
    motionFamily: "footwork",
    durationMs: 3_600,
    howTo: [
      "Lift the right foot just off the floor with the knee pointing down.",
      "Brush the toe plate forward from the knee.",
      "Brush the toe plate backward along the same path.",
      "Finish with the right foot lifted and ready to repeat.",
    ],
    phases: [
      phase("lift", "Right foot lifted; knee points down.", 0, -3, -1, "left", { leftKnee: 12, rightHip: -10, rightKnee: 32, rightFoot: -15 }),
      phase("brush-forward", "Brush the right toe forward.", 0.36, -2, -1, "left", { leftKnee: 13, rightHip: -24, rightKnee: 18, rightFoot: -36 }),
      phase("brush-back", "Brush the right toe backward.", 0.68, -3, -2, "left", { leftKnee: 13, rightHip: 13, rightKnee: 30, rightFoot: 24 }),
      phase("lift-again", "Return to the lifted starting foot.", 1, -3, -1, "left", { leftKnee: 12, rightHip: -10, rightKnee: 32, rightFoot: -15 }),
    ],
  }),
  movement({
    id: "flap",
    title: "Flap",
    discipline: "Tap",
    description: "Brush forward, then step onto the same foot so the two sounds travel.",
    preferredView: "side",
    startingPose: "Stand over the left leg with the right foot released.",
    motionFamily: "footwork",
    durationMs: 3_800,
    howTo: [
      "Lift the right foot slightly with the knee relaxed.",
      "Brush the right toe plate forward.",
      "Place the right ball of the foot and transfer weight onto it.",
      "Bring the left foot under the body to reset.",
    ],
    phases: [
      phase("lift", "Right foot lifted and released.", 0, -4, -1, "left", { leftKnee: 13, rightHip: -10, rightKnee: 32, rightFoot: -18 }),
      phase("brush", "Brush the right toe forward.", 0.28, -2, -1, "left", { leftKnee: 14, rightHip: -25, rightKnee: 19, rightFoot: -38 }),
      phase("step", "Place the right ball and transfer weight.", 0.58, 8, 1, "right", { leftHip: -14, leftKnee: 12, rightHip: 8, rightKnee: -18, rightFoot: -8 }),
      phase("reset", "Bring the feet back under the body.", 1, -4, -1, "left", { leftKnee: 13, rightHip: -10, rightKnee: 32, rightFoot: -18 }),
    ],
  }),
  movement({
    id: "stepBallChange",
    title: "Step–ball–change",
    discipline: "Tap",
    description: "Step, place the ball of the other foot behind, and replace weight onto the first foot.",
    preferredView: "front",
    startingPose: "Stand with the right foot free and both knees soft.",
    motionFamily: "footwork",
    durationMs: 4_200,
    howTo: [
      "Step onto the right foot.",
      "Place the ball of the left foot slightly behind the right and shift weight to it.",
      "Replace weight onto the right foot.",
      "Keep all three weight changes underneath the body.",
    ],
    phases: [
      phase("ready", "Right foot is free.", 0, -4, 1, "left", { leftKnee: 13, rightKnee: -7 }),
      phase("step", "Step onto the right foot.", 0.27, 7, 0, "right", { leftHip: -18, leftKnee: 14, rightHip: 8, rightKnee: -18 }),
      phase("ball", "Place the left ball behind and shift onto it.", 0.53, -2, 1, "left", { leftHip: 18, leftKnee: 28, leftFoot: 18, rightKnee: -10 }),
      phase("change", "Replace weight onto the right foot.", 0.76, 7, 0, "right", { leftHip: -12, leftKnee: 12, rightHip: 7, rightKnee: -17 }),
      phase("ready-again", "Return to the ready position.", 1, -4, 1, "left", { leftKnee: 13, rightKnee: -7 }),
    ],
    reducedPhaseIndexes: [0, 2, 3],
  }),
  movement({
    id: "jazzSquare",
    title: "Jazz square",
    discipline: "Jazz",
    description: "Cross in front, step back, step side, and close to trace a square.",
    preferredView: "front",
    startingPose: "Stand with feet under the hips and the right foot free.",
    motionFamily: "travel",
    durationMs: 5_000,
    howTo: [
      "Cross the right foot in front of the left.",
      "Step the left foot backward.",
      "Step the right foot to the right side.",
      "Bring the left foot beside the right to complete the square.",
    ],
    phases: [
      phase("ready", "Feet begin under the hips.", 0, 0, 1, "center", { leftKnee: 8, rightKnee: -8 }),
      phase("cross", "Cross the right foot in front.", 0.22, -3, 0, "right", { leftHip: -8, leftKnee: 10, rightHip: -28, rightKnee: -24, rightFoot: 16 }),
      phase("back", "Step the left foot backward.", 0.46, -5, 1, "left", { leftHip: 24, leftKnee: 26, rightHip: 5, rightKnee: -12 }),
      phase("side", "Step the right foot to the side.", 0.7, 9, 0, "right", { leftHip: -8, leftKnee: 10, rightHip: 28, rightKnee: -18 }),
      phase("close", "Close the left foot to finish the square.", 1, 0, 1, "center", { leftKnee: 8, rightKnee: -8 }),
    ],
    reducedPhaseIndexes: [0, 2, 4],
  }),
  movement({
    id: "stepTouch",
    title: "Step touch",
    discipline: "Jazz",
    description: "Step sideways, transfer weight, and touch the free foot beside the standing foot.",
    preferredView: "front",
    startingPose: "Stand with feet under the hips and knees soft.",
    motionFamily: "travel",
    durationMs: 4_200,
    allowedWithBurqa: true,
    howTo: [
      "Step the right foot to the right.",
      "Transfer weight fully onto the right foot.",
      "Touch the left toes beside the right foot without transferring weight.",
      "Step left and repeat in the other direction.",
    ],
    phases: [
      phase("center", "Feet begin under the hips.", 0, 0, 1, "center", { leftKnee: 9, rightKnee: -9 }),
      phase("step-right", "Step and transfer weight to the right.", 0.28, 12, 0, "right", { leftHip: -24, leftKnee: 14, rightHip: 18, rightKnee: -18 }),
      phase("touch", "Touch the left toes beside the right foot.", 0.5, 10, 1, "right", { leftHip: 10, leftKnee: 24, leftFoot: 18, rightKnee: -15 }),
      phase("step-left", "Step and transfer weight to the left.", 0.78, -12, 0, "left", { leftHip: -18, leftKnee: 18, rightHip: 24, rightKnee: -14 }),
      phase("center-again", "Return to the centered base.", 1, 0, 1, "center", { leftKnee: 9, rightKnee: -9 }),
    ],
    reducedPhaseIndexes: [0, 2, 4],
  }),
  movement({
    id: "pasDeBourree",
    title: "Pas de bourrée",
    discipline: "Jazz",
    description: "Step behind, open to the side, and cross or step forward in three weight changes.",
    preferredView: "front",
    startingPose: "Stand over the right leg with the left foot free.",
    motionFamily: "travel",
    durationMs: 4_400,
    howTo: [
      "Step the left foot behind the right.",
      "Step the right foot open to the side.",
      "Step the left foot forward or across.",
      "Keep the three weight changes even: behind, side, front.",
    ],
    phases: [
      phase("ready", "Left foot is free.", 0, 4, 1, "right", { leftKnee: 11, rightKnee: -12 }),
      phase("behind", "Step the left foot behind.", 0.28, -3, 1, "left", { leftHip: 22, leftKnee: 28, leftFoot: 14, rightKnee: -10 }),
      phase("side", "Step the right foot open.", 0.55, 8, 0, "right", { leftKnee: 10, rightHip: 26, rightKnee: -20 }),
      phase("front", "Step the left foot forward or across.", 0.78, -3, 0, "left", { leftHip: -26, leftKnee: 22, rightKnee: -9 }),
      phase("ready-again", "Return to the ready side.", 1, 4, 1, "right", { leftKnee: 11, rightKnee: -12 }),
    ],
    reducedPhaseIndexes: [0, 2, 3],
  }),
  movement({
    id: "pivotTurn",
    title: "Pivot turn",
    discipline: "Jazz",
    description: "Step forward, rotate on the balls of both feet, and settle facing the opposite direction.",
    preferredView: "side",
    startingPose: "Stand with the right foot free and enough clear floor to turn.",
    motionFamily: "travel",
    durationMs: 5_200,
    howTo: [
      "Step the right foot forward.",
      "Lift both heels slightly so the balls of the feet can rotate.",
      "Turn the body one half-turn to the left without twisting a planted knee.",
      "Lower the heels and finish with weight balanced between the feet.",
    ],
    phases: [
      phase("ready", "Right foot is free.", 0, -4, 1, "left", { leftKnee: 10, rightKnee: -8 }),
      phase("step", "Step the right foot forward.", 0.27, 8, 0, "right", { leftHip: -12, leftKnee: 10, rightHip: -20, rightKnee: -24 }),
      phase("pivot", "Lift the heels and rotate through the half-turn.", 0.56, 5, -2, "center", { torso: 18, pelvis: 28, leftKnee: 14, rightKnee: -14, leftFoot: 32, rightFoot: -32 }, 8, 0.72, 1),
      phase("arrive", "Lower the heels facing the new direction.", 0.76, -7, 1, "left", { torso: -8, pelvis: -12, leftHip: 12, leftKnee: 18, rightHip: 4, rightKnee: -10 }, -3, -1, 1),
      phase("ready-again", "Unwind slowly to repeat the demonstration.", 1, -4, 1, "left", { leftKnee: 10, rightKnee: -8 }),
    ],
    reducedPhaseIndexes: [0, 2, 3],
  }),
  movement({
    id: "kickBallChange",
    title: "Kick–ball–change",
    discipline: "Jazz",
    description: "Kick low, place the ball of that foot under the body, and replace weight onto the other foot.",
    preferredView: "side",
    startingPose: "Stand over the left leg with the right knee free.",
    motionFamily: "footwork",
    durationMs: 4_200,
    howTo: [
      "Lift the right knee and extend a low kick.",
      "Retract the lower leg before placing the ball of the right foot under the hip.",
      "Transfer weight briefly to the right ball.",
      "Replace weight onto the left foot.",
    ],
    phases: [
      phase("ready", "Weight stays over the left foot.", 0, -4, 1, "left", { leftKnee: 12, rightKnee: -8 }),
      phase("kick", "Lift the knee and extend a low right kick.", 0.28, -3, -3, "left", { leftKnee: 14, rightHip: -34, rightKnee: 5, rightFoot: -24 }),
      phase("ball", "Place the right ball under the hip.", 0.55, 5, 1, "right", { leftKnee: 12, rightHip: 8, rightKnee: -24, rightFoot: -14 }),
      phase("change", "Replace weight onto the left foot.", 0.76, -5, 1, "left", { leftHip: -7, leftKnee: 18, rightKnee: -10 }),
      phase("ready-again", "Return to the ready position.", 1, -4, 1, "left", { leftKnee: 12, rightKnee: -8 }),
    ],
    reducedPhaseIndexes: [0, 1, 3],
  }),
  movement({
    id: "tripleStep",
    title: "Triple step",
    discipline: "Swing",
    description: "Travel side, close, side through three compact weight changes.",
    preferredView: "front",
    startingPose: "Stand with knees springy and weight over the left foot.",
    motionFamily: "swing",
    durationMs: 3_900,
    howTo: [
      "Step the right foot a small distance to the right.",
      "Bring the left foot close to the right and transfer weight briefly.",
      "Step the right foot to the right again.",
      "Keep the rhythm compact: step, close, step.",
    ],
    phases: [
      phase("ready", "Weight begins over the left foot.", 0, -4, 2, "left", { leftKnee: 15, rightKnee: -10, leftElbow: -22, rightElbow: 22 }),
      phase("side", "Step right.", 0.28, 8, -1, "right", { leftHip: -18, leftKnee: 14, rightHip: 22, rightKnee: -20, leftElbow: -34, rightElbow: 34 }),
      phase("close", "Close the left foot toward the right.", 0.53, 5, 2, "left", { leftHip: 10, leftKnee: 24, rightKnee: -13, leftElbow: -18, rightElbow: 18 }),
      phase("side-again", "Step right again.", 0.76, 11, -1, "right", { leftHip: -15, leftKnee: 13, rightHip: 22, rightKnee: -21, leftElbow: -34, rightElbow: 34 }),
      phase("ready-again", "Return to the starting side.", 1, -4, 2, "left", { leftKnee: 15, rightKnee: -10, leftElbow: -22, rightElbow: 22 }),
    ],
    reducedPhaseIndexes: [0, 2, 3],
  }),
  movement({
    id: "rockStep",
    title: "Rock step",
    discipline: "Swing",
    description: "Step one foot behind, transfer back briefly, and return weight to the front foot.",
    preferredView: "side",
    startingPose: "Stand over the left foot with the right foot ready to travel back.",
    motionFamily: "swing",
    durationMs: 3_700,
    allowedWithBurqa: true,
    howTo: [
      "Reach the right foot a short distance behind.",
      "Transfer weight onto the ball of the right foot while the front heel stays available.",
      "Return weight forward onto the left foot.",
      "Bring the right foot back underneath the body.",
    ],
    phases: [
      phase("ready", "Weight begins over the left foot.", 0, -3, 2, "left", { leftKnee: 14, rightKnee: -10, leftElbow: -24, rightElbow: 24 }),
      phase("rock-back", "Reach and transfer onto the right ball behind.", 0.42, -11, 3, "right", { leftHip: -8, leftKnee: 10, rightHip: 30, rightKnee: -28, rightFoot: 14, leftElbow: -36, rightElbow: 36 }),
      phase("replace", "Return weight forward to the left foot.", 0.72, 5, -1, "left", { leftHip: -14, leftKnee: 20, rightKnee: -9, leftElbow: -18, rightElbow: 18 }),
      phase("ready-again", "Bring the right foot under the body.", 1, -3, 2, "left", { leftKnee: 14, rightKnee: -10, leftElbow: -24, rightElbow: 24 }),
    ],
  }),
  movement({
    id: "lindyBasic",
    title: "Lindy basic",
    discipline: "Swing",
    description: "Combine a rock step with two triple steps across eight counts.",
    preferredView: "front",
    startingPose: "Stand with knees springy and the right foot ready to rock back.",
    motionFamily: "swing",
    durationMs: 7_200,
    howTo: [
      "Rock the right foot back, then replace weight onto the left.",
      "Triple step right–left–right.",
      "Triple step left–right–left.",
      "Keep the body pulse small and let every footfall receive weight before the next.",
    ],
    phases: [
      phase("ready", "Begin over the left foot.", 0, -3, 2, "left", { leftKnee: 15, rightKnee: -10, leftElbow: -24, rightElbow: 24 }),
      phase("rock", "Rock back onto the right ball.", 0.15, -9, 3, "right", { leftKnee: 10, rightHip: 28, rightKnee: -26, leftElbow: -36, rightElbow: 36 }),
      phase("replace", "Replace forward onto the left.", 0.28, 3, -1, "left", { leftKnee: 20, rightKnee: -9, leftElbow: -18, rightElbow: 18 }),
      phase("triple-right", "Travel right–left–right.", 0.52, 11, 1, "right", { leftHip: 10, leftKnee: 22, rightHip: 20, rightKnee: -20, leftElbow: -38, rightElbow: 38 }),
      phase("triple-left", "Travel left–right–left.", 0.78, -11, 1, "left", { leftHip: -20, leftKnee: 20, rightHip: -10, rightKnee: -22, leftElbow: -18, rightElbow: 18 }),
      phase("ready-again", "Return to the beginning of the eight-count.", 1, -3, 2, "left", { leftKnee: 15, rightKnee: -10, leftElbow: -24, rightElbow: 24 }),
    ],
    reducedPhaseIndexes: [0, 3, 4],
  }),
  movement({
    id: "charleston",
    title: "Charleston basic",
    discipline: "Swing",
    description: "Touch back, step forward, kick forward, and step back through an eight-count pattern.",
    preferredView: "side",
    startingPose: "Stand over the left foot with the right foot free.",
    motionFamily: "swing",
    durationMs: 6_800,
    howTo: [
      "Touch the right toes behind without transferring weight.",
      "Step forward onto the right foot.",
      "Swing the left leg through into a low forward kick.",
      "Step back onto the left and return the right foot under the body.",
    ],
    phases: [
      phase("ready", "Weight begins over the left foot.", 0, -4, 2, "left", { leftKnee: 15, rightKnee: -10, leftElbow: -26, rightElbow: 26 }),
      phase("touch-back", "Touch the right toes behind.", 0.2, -5, 1, "left", { leftKnee: 14, rightHip: 32, rightKnee: -28, rightFoot: 16 }),
      phase("step-forward", "Step forward onto the right foot.", 0.42, 7, -1, "right", { leftHip: -16, leftKnee: 12, rightHip: -20, rightKnee: -22 }),
      phase("kick", "Swing the left leg into a low forward kick.", 0.65, 6, -4, "right", { leftHip: -38, leftKnee: 5, leftFoot: -18, rightKnee: -18, leftElbow: -38, rightElbow: 38 }),
      phase("step-back", "Step back onto the left foot.", 0.82, -5, 2, "left", { leftHip: 18, leftKnee: 24, rightKnee: -10 }),
      phase("ready-again", "Return to the ready position.", 1, -4, 2, "left", { leftKnee: 15, rightKnee: -10, leftElbow: -26, rightElbow: 26 }),
    ],
    reducedPhaseIndexes: [0, 2, 3],
  }),
  movement({
    id: "tuckTurn",
    title: "Tuck turn footwork",
    discipline: "Swing",
    description: "Rock back, compress forward, turn through a triple step, and settle.",
    preferredView: "side",
    startingPose: "Stand with knees springy and the right foot ready to rock back.",
    motionFamily: "swing",
    durationMs: 6_200,
    howTo: [
      "Rock the right foot back and replace onto the left.",
      "Take a small forward step and allow the body to compress toward center.",
      "Turn through a compact right–left–right triple step.",
      "Finish facing the new direction with weight settled over the final foot.",
    ],
    phases: [
      phase("ready", "Begin over the left foot.", 0, -3, 2, "left", { leftKnee: 15, rightKnee: -10, leftElbow: -28, rightElbow: 28 }),
      phase("rock", "Rock back onto the right ball.", 0.2, -10, 3, "right", { leftKnee: 10, rightHip: 28, rightKnee: -26, leftElbow: -38, rightElbow: 38 }),
      phase("compress", "Replace forward and gather toward the center.", 0.4, 3, 3, "left", { torso: 3, leftKnee: 24, rightKnee: -16, leftShoulder: 34, leftElbow: -62, rightShoulder: -34, rightElbow: 62 }, 0, 1.05, 0.94),
      phase("turn", "Turn through the compact triple step.", 0.68, 8, -2, "right", { torso: 16, pelvis: 24, leftHip: 12, leftKnee: 20, rightHip: 18, rightKnee: -20, leftShoulder: 72, leftElbow: -24, rightShoulder: -72, rightElbow: 24 }, 7, 0.74, 1),
      phase("settle", "Settle over the final foot.", 0.84, -5, 1, "left", { torso: -5, pelvis: -10, leftKnee: 18, rightKnee: -10, leftShoulder: 18, leftElbow: -38, rightShoulder: -18, rightElbow: 38 }, -2, -1, 1),
      phase("ready-again", "Unwind slowly to repeat.", 1, -3, 2, "left", { leftKnee: 15, rightKnee: -10, leftElbow: -28, rightElbow: 28 }),
    ],
    reducedPhaseIndexes: [0, 2, 4],
  }),
];
